---
# tasks file for prerequisites

- name: install prerequisites
  include_tasks: install.yml

- name: install and configure ufw
  include_tasks: ufw.yml
  tags: ufw

- name: configure hostname
  include_tasks: hostname.yml
  tags: hostname

- name: configure timedate
  include_tasks: timedate.yml
  tags: timedate
